prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: pac-backend
        static_configs:
          - targets: ["backend.backend"]
  ingress:
    enabled: true
    hosts:
      - conference.prometheus
    path: /
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: grafana-dashboard-config
  ingress:
    enabled: true
    hosts:
      - conference.grafana
    path: /