grafana:
  ingress:
    enabled: true
    hosts:
      - conference.grafana
    path: /
prometheus:
  ingress:
    enabled: true
    hosts:
      - conference.prometheus
    path: /
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false